name: Deploy Django to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: django-app
  ECS_CLUSTER: django-cluster
  ECS_SERVICE: django-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <AWS_ECR_URL>

      - name: Build and Push Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:latest ./django-app
          docker tag $ECR_REPOSITORY:latest <AWS_ECR_URL>/$ECR_REPOSITORY:latest
          docker push <AWS_ECR_URL>/$ECR_REPOSITORY:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Update ECS Task Definition
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
